/** Country calling codes for phone inputs */
const COUNTRY_CALLING_CODES = [
  { iso: "AFG", name: "Afghanistan", dial: "+93" },
  { iso: "ALB", name: "Albania", dial: "+355" },
  { iso: "DZA", name: "Algeria", dial: "+213" },
  { iso: "ASM", name: "American Samoa", dial: "+1" },
  { iso: "AND", name: "Andorra", dial: "+376" },
  { iso: "AGO", name: "Angola", dial: "+244" },
  { iso: "AIA", name: "Anguilla", dial: "+1" },
  { iso: "ATG", name: "Antigua and Barbuda", dial: "+1" },
  { iso: "ARG", name: "Argentina", dial: "+54" },
  { iso: "ARM", name: "Armenia", dial: "+374" },
  { iso: "ABW", name: "Aruba", dial: "+297" },
  { iso: "AUS", name: "Australia", dial: "+61" },
  { iso: "AUT", name: "Austria", dial: "+43" },
  { iso: "AZE", name: "Azerbaijan", dial: "+994" },
  { iso: "BHS", name: "Bahamas", dial: "+1" },
  { iso: "BHR", name: "Bahrain", dial: "+973" },
  { iso: "BGD", name: "Bangladesh", dial: "+880" },
  { iso: "BRB", name: "Barbados", dial: "+1" },
  { iso: "BLR", name: "Belarus", dial: "+375" },
  { iso: "BEL", name: "Belgium", dial: "+32" },
  { iso: "BLZ", name: "Belize", dial: "+501" },
  { iso: "BEN", name: "Benin", dial: "+229" },
  { iso: "BMU", name: "Bermuda", dial: "+1" },
  { iso: "BTN", name: "Bhutan", dial: "+975" },
  { iso: "BOL", name: "Bolivia", dial: "+591" },
  { iso: "BIH", name: "Bosnia and Herzegovina", dial: "+387" },
  { iso: "BWA", name: "Botswana", dial: "+267" },
  { iso: "BRA", name: "Brazil", dial: "+55" },
  { iso: "VGB", name: "British Virgin Islands", dial: "+1" },
  { iso: "BRN", name: "Brunei", dial: "+673" },
  { iso: "BGR", name: "Bulgaria", dial: "+359" },
  { iso: "BFA", name: "Burkina Faso", dial: "+226" },
  { iso: "BDI", name: "Burundi", dial: "+257" },
  { iso: "KHM", name: "Cambodia", dial: "+855" },
  { iso: "CMR", name: "Cameroon", dial: "+237" },
  { iso: "CAN", name: "Canada", dial: "+1" },
  { iso: "CPV", name: "Cape Verde", dial: "+238" },
  { iso: "CYM", name: "Cayman Islands", dial: "+1" },
  { iso: "CAF", name: "Central African Republic", dial: "+236" },
  { iso: "TCD", name: "Chad", dial: "+235" },
  { iso: "CHL", name: "Chile", dial: "+56" },
  { iso: "CHN", name: "China", dial: "+86" },
  { iso: "COL", name: "Colombia", dial: "+57" },
  { iso: "COM", name: "Comoros", dial: "+269" },
  { iso: "COG", name: "Congo", dial: "+242" },
  { iso: "COD", name: "Congo (DRC)", dial: "+243" },
  { iso: "COK", name: "Cook Islands", dial: "+682" },
  { iso: "CRI", name: "Costa Rica", dial: "+506" },
  { iso: "HRV", name: "Croatia", dial: "+385" },
  { iso: "CUB", name: "Cuba", dial: "+53" },
  { iso: "CYP", name: "Cyprus", dial: "+357" },
  { iso: "CZE", name: "Czech Republic", dial: "+420" },
  { iso: "DNK", name: "Denmark", dial: "+45" },
  { iso: "DJI", name: "Djibouti", dial: "+253" },
  { iso: "DMA", name: "Dominica", dial: "+1" },
  { iso: "DOM", name: "Dominican Republic", dial: "+1" },
  { iso: "ECU", name: "Ecuador", dial: "+593" },
  { iso: "EGY", name: "Egypt", dial: "+20" },
  { iso: "SLV", name: "El Salvador", dial: "+503" },
  { iso: "GNQ", name: "Equatorial Guinea", dial: "+240" },
  { iso: "ERI", name: "Eritrea", dial: "+291" },
  { iso: "EST", name: "Estonia", dial: "+372" },
  { iso: "SWZ", name: "Eswatini", dial: "+268" },
  { iso: "ETH", name: "Ethiopia", dial: "+251" },
  { iso: "FLK", name: "Falkland Islands", dial: "+500" },
  { iso: "FRO", name: "Faroe Islands", dial: "+298" },
  { iso: "FJI", name: "Fiji", dial: "+679" },
  { iso: "FIN", name: "Finland", dial: "+358" },
  { iso: "FRA", name: "France", dial: "+33" },
  { iso: "GUF", name: "French Guiana", dial: "+594" },
  { iso: "PYF", name: "French Polynesia", dial: "+689" },
  { iso: "GAB", name: "Gabon", dial: "+241" },
  { iso: "GMB", name: "Gambia", dial: "+220" },
  { iso: "GEO", name: "Georgia", dial: "+995" },
  { iso: "DEU", name: "Germany", dial: "+49" },
  { iso: "GHA", name: "Ghana", dial: "+233" },
  { iso: "GIB", name: "Gibraltar", dial: "+350" },
  { iso: "GRC", name: "Greece", dial: "+30" },
  { iso: "GRL", name: "Greenland", dial: "+299" },
  { iso: "GRD", name: "Grenada", dial: "+1" },
  { iso: "GLP", name: "Guadeloupe", dial: "+590" },
  { iso: "GUM", name: "Guam", dial: "+1" },
  { iso: "GTM", name: "Guatemala", dial: "+502" },
  { iso: "GIN", name: "Guinea", dial: "+224" },
  { iso: "GNB", name: "Guinea-Bissau", dial: "+245" },
  { iso: "GUY", name: "Guyana", dial: "+592" },
  { iso: "HTI", name: "Haiti", dial: "+509" },
  { iso: "HND", name: "Honduras", dial: "+504" },
  { iso: "HKG", name: "Hong Kong", dial: "+852" },
  { iso: "HUN", name: "Hungary", dial: "+36" },
  { iso: "ISL", name: "Iceland", dial: "+354" },
  { iso: "IND", name: "India", dial: "+91" },
  { iso: "IDN", name: "Indonesia", dial: "+62" },
  { iso: "IRN", name: "Iran", dial: "+98" },
  { iso: "IRQ", name: "Iraq", dial: "+964" },
  { iso: "IRL", name: "Ireland", dial: "+353" },
  { iso: "ISR", name: "Israel", dial: "+972" },
  { iso: "ITA", name: "Italy", dial: "+39" },
  { iso: "CIV", name: "Ivory Coast", dial: "+225" },
  { iso: "JAM", name: "Jamaica", dial: "+1" },
  { iso: "JPN", name: "Japan", dial: "+81" },
  { iso: "JOR", name: "Jordan", dial: "+962" },
  { iso: "KAZ", name: "Kazakhstan", dial: "+7" },
  { iso: "KEN", name: "Kenya", dial: "+254" },
  { iso: "KIR", name: "Kiribati", dial: "+686" },
  { iso: "KWT", name: "Kuwait", dial: "+965" },
  { iso: "KGZ", name: "Kyrgyzstan", dial: "+996" },
  { iso: "LAO", name: "Laos", dial: "+856" },
  { iso: "LVA", name: "Latvia", dial: "+371" },
  { iso: "LBN", name: "Lebanon", dial: "+961" },
  { iso: "LSO", name: "Lesotho", dial: "+266" },
  { iso: "LBR", name: "Liberia", dial: "+231" },
  { iso: "LBY", name: "Libya", dial: "+218" },
  { iso: "LIE", name: "Liechtenstein", dial: "+423" },
  { iso: "LTU", name: "Lithuania", dial: "+370" },
  { iso: "LUX", name: "Luxembourg", dial: "+352" },
  { iso: "MAC", name: "Macau", dial: "+853" },
  { iso: "MDG", name: "Madagascar", dial: "+261" },
  { iso: "MWI", name: "Malawi", dial: "+265" },
  { iso: "MYS", name: "Malaysia", dial: "+60" },
  { iso: "MDV", name: "Maldives", dial: "+960" },
  { iso: "MLI", name: "Mali", dial: "+223" },
  { iso: "MLT", name: "Malta", dial: "+356" },
  { iso: "MHL", name: "Marshall Islands", dial: "+692" },
  { iso: "MTQ", name: "Martinique", dial: "+596" },
  { iso: "MRT", name: "Mauritania", dial: "+222" },
  { iso: "MUS", name: "Mauritius", dial: "+230" },
  { iso: "MEX", name: "Mexico", dial: "+52" },
  { iso: "FSM", name: "Micronesia", dial: "+691" },
  { iso: "MDA", name: "Moldova", dial: "+373" },
  { iso: "MCO", name: "Monaco", dial: "+377" },
  { iso: "MNG", name: "Mongolia", dial: "+976" },
  { iso: "MNE", name: "Montenegro", dial: "+382" },
  { iso: "MSR", name: "Montserrat", dial: "+1" },
  { iso: "MAR", name: "Morocco", dial: "+212" },
  { iso: "MOZ", name: "Mozambique", dial: "+258" },
  { iso: "MMR", name: "Myanmar", dial: "+95" },
  { iso: "NAM", name: "Namibia", dial: "+264" },
  { iso: "NRU", name: "Nauru", dial: "+674" },
  { iso: "NPL", name: "Nepal", dial: "+977" },
  { iso: "NLD", name: "Netherlands", dial: "+31" },
  { iso: "NCL", name: "New Caledonia", dial: "+687" },
  { iso: "NZL", name: "New Zealand", dial: "+64" },
  { iso: "NIC", name: "Nicaragua", dial: "+505" },
  { iso: "NER", name: "Niger", dial: "+227" },
  { iso: "NGA", name: "Nigeria", dial: "+234" },
  { iso: "NIU", name: "Niue", dial: "+683" },
  { iso: "PRK", name: "North Korea", dial: "+850" },
  { iso: "MKD", name: "North Macedonia", dial: "+389" },
  { iso: "MNP", name: "Northern Mariana Islands", dial: "+1" },
  { iso: "NOR", name: "Norway", dial: "+47" },
  { iso: "OMN", name: "Oman", dial: "+968" },
  { iso: "PAK", name: "Pakistan", dial: "+92" },
  { iso: "PLW", name: "Palau", dial: "+680" },
  { iso: "PSE", name: "Palestine", dial: "+970" },
  { iso: "PAN", name: "Panama", dial: "+507" },
  { iso: "PNG", name: "Papua New Guinea", dial: "+675" },
  { iso: "PRY", name: "Paraguay", dial: "+595" },
  { iso: "PER", name: "Peru", dial: "+51" },
  { iso: "PHL", name: "Philippines", dial: "+63" },
  { iso: "POL", name: "Poland", dial: "+48" },
  { iso: "PRT", name: "Portugal", dial: "+351" },
  { iso: "PRI", name: "Puerto Rico", dial: "+1" },
  { iso: "QAT", name: "Qatar", dial: "+974" },
  { iso: "REU", name: "Reunion", dial: "+262" },
  { iso: "ROU", name: "Romania", dial: "+40" },
  { iso: "RUS", name: "Russia", dial: "+7" },
  { iso: "RWA", name: "Rwanda", dial: "+250" },
  { iso: "KNA", name: "Saint Kitts and Nevis", dial: "+1" },
  { iso: "LCA", name: "Saint Lucia", dial: "+1" },
  { iso: "SPM", name: "Saint Pierre and Miquelon", dial: "+508" },
  { iso: "VCT", name: "Saint Vincent and the Grenadines", dial: "+1" },
  { iso: "WSM", name: "Samoa", dial: "+685" },
  { iso: "SMR", name: "San Marino", dial: "+378" },
  { iso: "STP", name: "Sao Tome and Principe", dial: "+239" },
  { iso: "SAU", name: "Saudi Arabia", dial: "+966" },
  { iso: "SEN", name: "Senegal", dial: "+221" },
  { iso: "SRB", name: "Serbia", dial: "+381" },
  { iso: "SYC", name: "Seychelles", dial: "+248" },
  { iso: "SLE", name: "Sierra Leone", dial: "+232" },
  { iso: "SGP", name: "Singapore", dial: "+65" },
  { iso: "SVK", name: "Slovakia", dial: "+421" },
  { iso: "SVN", name: "Slovenia", dial: "+386" },
  { iso: "SLB", name: "Solomon Islands", dial: "+677" },
  { iso: "SOM", name: "Somalia", dial: "+252" },
  { iso: "RSA", name: "South Africa", dial: "+27" },
  { iso: "KOR", name: "South Korea", dial: "+82" },
  { iso: "SSD", name: "South Sudan", dial: "+211" },
  { iso: "ESP", name: "Spain", dial: "+34" },
  { iso: "LKA", name: "Sri Lanka", dial: "+94" },
  { iso: "SDN", name: "Sudan", dial: "+249" },
  { iso: "SUR", name: "Suriname", dial: "+597" },
  { iso: "SWE", name: "Sweden", dial: "+46" },
  { iso: "CHE", name: "Switzerland", dial: "+41" },
  { iso: "SYR", name: "Syria", dial: "+963" },
  { iso: "TWN", name: "Taiwan", dial: "+886" },
  { iso: "TJK", name: "Tajikistan", dial: "+992" },
  { iso: "TZA", name: "Tanzania", dial: "+255" },
  { iso: "THA", name: "Thailand", dial: "+66" },
  { iso: "TLS", name: "Timor-Leste", dial: "+670" },
  { iso: "TGO", name: "Togo", dial: "+228" },
  { iso: "TKL", name: "Tokelau", dial: "+690" },
  { iso: "TON", name: "Tonga", dial: "+676" },
  { iso: "TTO", name: "Trinidad and Tobago", dial: "+1" },
  { iso: "TUN", name: "Tunisia", dial: "+216" },
  { iso: "TUR", name: "Turkey", dial: "+90" },
  { iso: "TKM", name: "Turkmenistan", dial: "+993" },
  { iso: "TCA", name: "Turks and Caicos Islands", dial: "+1" },
  { iso: "TUV", name: "Tuvalu", dial: "+688" },
  { iso: "UGA", name: "Uganda", dial: "+256" },
  { iso: "UKR", name: "Ukraine", dial: "+380" },
  { iso: "ARE", name: "United Arab Emirates", dial: "+971" },
  { iso: "GBR", name: "United Kingdom", dial: "+44" },
  { iso: "USA", name: "United States", dial: "+1" },
  { iso: "URY", name: "Uruguay", dial: "+598" },
  { iso: "UZB", name: "Uzbekistan", dial: "+998" },
  { iso: "VUT", name: "Vanuatu", dial: "+678" },
  { iso: "VAT", name: "Vatican City", dial: "+39" },
  { iso: "VEN", name: "Venezuela", dial: "+58" },
  { iso: "VNM", name: "Vietnam", dial: "+84" },
  { iso: "VIR", name: "Virgin Islands (U.S.)", dial: "+1" },
  { iso: "WLF", name: "Wallis and Futuna", dial: "+681" },
  { iso: "YEM", name: "Yemen", dial: "+967" },
  { iso: "ZMB", name: "Zambia", dial: "+260" },
  { iso: "ZWE", name: "Zimbabwe", dial: "+263" },
];

function initCountryCodeSelects(defaultDial = "+1") {
  document.querySelectorAll('select#country-code, select[name="countryCode"]').forEach((select) => {
    const current =
      select.value ||
      select.querySelector("option[selected]")?.value ||
      defaultDial;

    select.innerHTML = "";

    [...COUNTRY_CALLING_CODES]
      .sort((a, b) => a.iso.localeCompare(b.iso))
      .forEach(({ iso, name, dial }) => {
        const option = document.createElement("option");
        option.value = dial;
        option.textContent = `${iso} (${dial})`;
        option.title = name;
        select.appendChild(option);
      });

    if ([...select.options].some((option) => option.value === current)) {
      select.value = current;
    } else {
      select.value = defaultDial;
    }
  });
}

document.addEventListener("DOMContentLoaded", () => initCountryCodeSelects("+1"));
